export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/jwt/create/',
    REGISTER: '/auth/users/',
    REFRESH_ACCESS_TOKEN: '/auth/jwt/refresh/',
    VERIFY_TOKEN: '/auth/jwt/verify/',
    ME: '/auth/me/',
    OTP_STATUS: (token: string) => `/otp/${token}/status/`,
    RESEND_OTP: '/otp/create/',
    RESEND_OTP_LOGIN: '/otp/resend-login/',
    VERIFY_OTP: '/otp/verify/',
    FORGOT_PASSWORD: '/auth/password/forgot/',
    RESET_PASSWORD: '/auth/password/reset/',
    PASSWORD_RESET_STATUS: (token: string) => `/auth/password/${token}/status/`,
    REQUEST_DELETE_ACCOUNT: '/auth/me/delete-account/',
    FORGOT_PASSWORD_AUTHED: '/auth/me/forgot-password/',
    ACCOUNT_DELETE_STATUS: (token: string) => `/auth/account-delete/${token}/status/`,
    CONFIRM_DELETE_ACCOUNT: '/auth/account-delete/confirm/',
    SESSIONS: '/auth/sessions/',
    SESSION: (id: string) => `/auth/sessions/${id}/`,
    LOGOUT_ALL: '/auth/sessions/logout-all/',
  },
  TASKS: {
    LIST: '/tasks/',
    TASK: (id: string) => `/tasks/${id}/`,
    PROJECTS: '/tasks/projects/',
    PROJECT: (id: string) => `/tasks/projects/${id}/`,
    PROJECT_TASKS: (projectId: string) => `/tasks/projects/${projectId}/tasks/`,
  },
  GOALS: {
    DASHBOARD: '/goals/',
    GOALS: '/goals/',
    GOAL: (id: string) => `/goals/${id}/`,
    MILESTONES: (goalId: string) => `/goals/${goalId}/milestones/`,
    MILESTONE: (goalId: string, milestoneId: string) =>
      `/goals/${goalId}/milestones/${milestoneId}/`,
  },
  WEALTH: {
    DASHBOARD: '/wealth/',
    TRANSACTIONS: '/wealth/transactions/',
    TRANSACTION: (id: string) => `/wealth/transactions/${id}/`,
    BUDGETS: '/wealth/budgets/',
    BUDGET: (id: string) => `/wealth/budgets/${id}/`,
  },
  TIME_TRACK: {
    DASHBOARD: '/time-track/',
    ENTRIES: '/time-track/entries/',
    ENTRY: (id: string) => `/time-track/entries/${id}/`,
    TRACKED_TASKS: '/time-track/tracked-tasks/',
    TRACKED_TASK: (taskId: string) => `/time-track/tracked-tasks/${taskId}/`,
    SETTINGS: '/time-track/settings/',
  },
  HABITS: {
    LIST: '/habits/',
    DAY: '/habits/day/',
    PACK: '/habits/pack/',
    HABIT: (id: string) => `/habits/${id}/`,
    TOGGLE: (id: string) => `/habits/${id}/toggle/`,
    ADJUST: (id: string) => `/habits/${id}/adjust/`,
    LOG: (id: string) => `/habits/${id}/log/`,
  },
  HEALTH: {
    DASHBOARD: '/health/',
    PROFILE: '/health/profile/',
    TARGETS: '/health/targets/',
    TODAY: '/health/today/',
    METRICS_ADJUST: '/health/metrics/adjust/',
    WEIGHT: '/health/weight/',
    SLEEP_SESSIONS: '/health/sleep-sessions/',
    SLEEP_SESSION: (id: string) => `/health/sleep-sessions/${id}/`,
    SLEEP_TOGGLE: '/health/sleep-sessions/toggle/',
    WORKOUTS: '/health/workouts/',
    MOOD: '/health/mood/',
  },
  PRAYER: {
    METHODS: '/prayer/methods/',
    PREFERENCES: '/prayer/preferences/',
    TIMINGS: '/prayer/timings/',
    TIMINGS_BY_CITY: '/prayer/timings-by-city/',
    DAY: '/prayer/day/',
    LOGS: '/prayer/logs/',
  },
  NOTES: {
    DASHBOARD: '/notes/',
    NOTES: '/notes/',
    NOTE: (id: string) => `/notes/${id}/`,
    PERMANENT: (id: string) => `/notes/${id}/permanent/`,
    RESTORE: (id: string) => `/notes/${id}/restore/`,
    ARCHIVE: (id: string) => `/notes/${id}/archive/`,
    DUPLICATE: (id: string) => `/notes/${id}/duplicate/`,
    BULK: '/notes/bulk/',
    RESTORE_VERSION: (id: string) => `/notes/${id}/versions/restore/`,
  },
  ASSISTANT: {
    CHAT: '/assistant/chat/',
    SPEECH: '/assistant/speech/',
    TRANSCRIBE: '/assistant/transcribe/',
    TRANSCRIBE_BASE64: '/assistant/transcribe/base64/',
    CONVERSATIONS: '/assistant/conversations/',
    CONVERSATION: (id: string) => `/assistant/conversations/${id}/`,
    DAILY_QUOTE: '/assistant/daily-quote/',
    GOALS_QUOTE: '/assistant/goals-quote/',
    INSIGHTS: '/assistant/insights/',
  },
} as const;
